name: Publish to NPM
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies and build
        run: yarn install && yarn build
      - name: Publish package to NPM
        run: |
          npm set //registry.npmjs.org/:_authToken ${{secrets.NPM_TOKEN}}
          npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

